
defaults:
  - wandb: defaults
  - hydra: defaults
  - cam_embd: defaults
  - _self_
general:
  device: 0
  random_seed: 0
  num_devices: 1
  mixed_precision: false
data:
  training_resolution: 256
  subset: -1
  input_images: 1
  origin_distances: false
  znear: 0.8
  zfar: 1.8
  fov: 51.98948897809546
  category: cars
  white_background: true
opt:
  iterations: 8
  base_lr: 0.00005
  batch_size: 4
  betas:
    - 0.9
    - 0.999
  loss: l2
  imgs_per_obj: 4
  ema:
    use: true
    update_every: 10
    update_after_step: 100
    beta: 0.9999
  lambda_lpips: 0.0
  pretrained_ckpt: null

model:
  max_sh_degree: 1
  inverted_x: false
  inverted_y: true
  name: SingleUNet
  depth_scale: 1.0
  depth_bias: 0.0
  network_without_offset: false
  network_with_offset: true
  attention_resolutions:
  - 16
  num_blocks: 4
  cross_view_attention: true
  base_dim: 128
  isotropic: false
  opacity_scale: 0.001
  opacity_bias: -3.0
  scale_scale: 0.001
  scale_bias: 0.02
  xyz_scale: 0.000001
  xyz_bias: 0.0

logging:
  ckpt_iterations: 1
  val_log: 10
  loss_log: 10
  loop_log: 10
  render_log: 100
